plugins:
  topic_custom_field_enabled:
    type: boolean
    default: true
    client: true
  topic_custom_field_name:
    type: string
    default: 'process_url'
    client: true
  topic_custom_field_type:
    type: enum
    default: 'string'
    client: true
    choices:
      - string
      - integer
      - boolean
      - json